title: Pierrick Girard # your name (or website title) here
logo: "/images/Photo_Github_Page.png?raw=true" # your photo (or logo) here
description: >
  <strong>Data Analyst | 15+ ans d’expérience</strong>
  <br>
  @SFR @SNCF
  <br><br>
  <strong>SQL • Python • Power BI • MS Azure</strong>
  <br><br>
  <span style="display:inline-block; width:100%; text-align:justify;">
    Fort de plus de 15 ans d’expérience dans de grands groupes et actuellement en poste à la <strong>SNCF</strong>, 
    je développe en parallèle une activité tournée vers la valorisation des <strong>données</strong> : 
    de la création de <strong>dashboards</strong> clairs à la mise en place de <strong>stratégies</strong> orientées résultats.  
    <br><br>
    Curieux et en apprentissage continu, je me forme à la <strong>data science</strong> et à l’<strong>intelligence artificielle</strong> 
    pour intégrer les dernières avancées technologiques dans mes missions.  
    <br><br>
    Convaincu que la donnée doit être comprise par tous, je partage régulièrement des contenus de vulgarisation afin de rendre la data accessible, 
    inspirante et actionnable pour les <strong>décideurs</strong> comme pour les passionnés.
  </span>
  <br><br>
  <a href="https://www.linkedin.com/in/pierrickgirard-montblancdata/">
    <img src="/assets/linkedin-svgrepo-com.svg" alt=" LinkedIn" width="40" style="margin-right:12px;">
  </a>
  <a href="https://github.com/MontblancData">
    <img src="/assets/github-mark.svg" alt=" GitHub" width="40">
  </a>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here


